- hosts: lh
  sudo: yes
  remote_user: {{ mac_user }}
  connection: local
  roles:
    - { role: homebrew, tags: [homebrew] }
    - { role: macenv, tags: [macenv] }
    - { role: dotfiles, tags: [dotfiles] }
