- name: Add homebrew tap repository
  homebrew_tap: tap={{ item }} state=installed
  with_items:
    - "{{ homebrew_taps }}"

- name: Update homebrew
  homebrew: update_homebrew=yes

- name: Install brew packages
  homebrew:
    name={{ item.name }}
    state={{ item.state | default('installed') }}
    install_options={{ item.install_options | default('latest') }}
  with_items:
    "{{ homebrew_packages }}"

- name: Install cask packages
  homebrew_cask:
    name={{ item.name }}
    state={{ item.state | default('installed') }}
  with_items:
    - "{{ homebrew_cask_packages }}"
